class SqliteMockData {
  static const List<Map<String, dynamic>> mockProducts = [
    {
      'id': 'mock-1',
      'categoryId': 'cat-1',
      'name': 'Áo Thun Unisex Big Size Premium',
      'description': 'Chất liệu thun cotton 100% co giãn tốt, thoáng mát, thích hợp cho người từ 80kg - 120kg.',
      'price': 189000.0,
      'stock': 45,
      'imageUrl': 'https://picsum.photos/300/300?random=1',
      'isActive': 1,
      'category_json': '{"id":"cat-1","name":"Áo Thun"}',
      'images_json': '[{"id":"img-1-1","image_url":"https://picsum.photos/300/300?random=1","is_thumbnail":true}]',
      'variants_json': '[{"id":"var-1-1","variant_name":"XL (75-85kg)","price":189000.0,"stock":20},{"id":"var-1-2","variant_name":"2XL (85-100kg)","price":199000.0,"stock":25}]',
    },
    {
      'id': 'mock-2',
      'categoryId': 'cat-2',
      'name': 'Quần Jean Baggy Nam Nữ Big Size',
      'description': 'Quần bò baggy form rộng chuẩn chất denim cao cấp, mặc cực thoải mái, trẻ trung năng động.',
      'price': 299000.0,
      'stock': 30,
      'imageUrl': 'https://picsum.photos/300/300?random=2',
      'isActive': 1,
      'category_json': '{"id":"cat-2","name":"Quần Jeans"}',
      'images_json': '[{"id":"img-2-1","image_url":"https://picsum.photos/300/300?random=2","is_thumbnail":true}]',
      'variants_json': '[{"id":"var-2-1","variant_name":"Size 36 (80-90kg)","price":299000.0,"stock":15},{"id":"var-2-2","variant_name":"Size 38 (90-105kg)","price":319000.0,"stock":15}]',
    },
    {
      'id': 'mock-3',
      'categoryId': 'cat-3',
      'name': 'Áo Khoác Bomber Big Size Họa Tiết',
      'description': 'Lớp lót dù gió ấm áp thoáng khí, kiểu dáng streetwear thời trang thời thượng.',
      'price': 350000.0,
      'stock': 12,
      'imageUrl': 'https://picsum.photos/300/300?random=3',
      'isActive': 1,
      'category_json': '{"id":"cat-3","name":"Áo Khoác"}',
      'images_json': '[{"id":"img-3-1","image_url":"https://picsum.photos/300/300?random=3","is_thumbnail":true}]',
      'variants_json': '[{"id":"var-3-1","variant_name":"Freesize < 110kg","price":350000.0,"stock":12}]',
    },
    {
      'id': 'mock-4',
      'categoryId': 'cat-4',
      'name': 'Đầm Suông Nữ Thun Cát Hàn Big Size',
      'description': 'Chất thun cát Hàn co giãn tốt, form suông giấu dáng cực đỉnh cho các bạn nữ mũm mĩm.',
      'price': 220000.0,
      'stock': 25,
      'imageUrl': 'https://picsum.photos/300/300?random=4',
      'isActive': 1,
      'category_json': '{"id":"cat-4","name":"Đầm Váy"}',
      'images_json': '[{"id":"img-4-1","image_url":"https://picsum.photos/300/300?random=4","is_thumbnail":true}]',
      'variants_json': '[{"id":"var-4-1","variant_name":"L (70-85kg)","price":220000.0,"stock":10},{"id":"var-4-2","variant_name":"XL (85-100kg)","price":230000.0,"stock":15}]',
    }
  ];
}
